package ch.cern.eam.wshub.core.services.workorders.entities;

import java.math.BigInteger;

public class WorkOrderActivityChecklistSignature  {

    private String workOrderCode;

    private BigInteger activityCodeValue;

    private String activityCodeAutoGenerated;

    private String note;

    private BigInteger jobSequence;

    private BigInteger sequenceNumber;

    String userCode;

    String password;

    String signatureType;

    public WorkOrderActivityChecklistSignature() {
        activityCodeAutoGenerated = "false";
    }

    public String getWorkOrderCode() {
        return workOrderCode;
    }

    public void setWorkOrderCode(String workOrderCode) {
        this.workOrderCode = workOrderCode;
    }

    public void setActivityCodeValue(String activityCodeValue) {
        this.activityCodeValue = new BigInteger(activityCodeValue);
    }

    public void setActivityCodeAutoGenerated(String activityCodeAutoGenerated) {
        this.activityCodeAutoGenerated = activityCodeAutoGenerated;
    }

    public String getNote() { return note; }

    public void setNote(String note) {
        this.note = note;
    }

    public BigInteger getJobSequence() {
        return jobSequence;
    }

    public void setSequence(BigInteger jobSequence) {
        this.jobSequence = jobSequence;
    }

    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    public void setSequenceNumber(BigInteger sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSignatureType() {
        return signatureType;
    }

    public void setSignatureType(String signatureType) {
        this.signatureType = signatureType;
    }

    public BigInteger getActivityCodeValue() {
        return activityCodeValue;
    }
}
